### ISSUE TITLE
Document the Configuration function/keyword

### ISSUE THREAD

**Issue by ykuijs** [MicrosoftDocs/PowerShell-Docs-DSC#53]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

2.0, 3.0

### Link to affected document

https://docs.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/configuration?view=dsc-2.0

### Description of the documentation error

All labels in the article are displaying Placeholder data, like '{{ Fill in the Synopsis }}'. This makes the article less useful.

### Suggested fix

Please replace the placeholders with the actual information.

**Comment by michaeltlombardi** [comment]
Thanks for reporting this, @ykuijs!

I've been doing some investigation work the last week or so when I'm able and to make a long and boring story short and clear:

The `Configuration` _function_ exported in the **PSDesiredStateConfiguration** module is not meant for end-users to call directly, it's used internally by the `Configuration` _keyword_ in PowerShell, which is why it hasn't been documented before. I'm going to be deleting those documents from the v2 and v3 docs to remove the confusion. We're undertaking longer term work to expand the documentation for those versions of DSC but in the meantime if you're looking to understand how to use the `Configuration` _keyword_, you can find that information [in the v1.1 documentation](https://docs.microsoft.com/powershell/dsc/configurations/configurations?view=dsc-1.1).

When those documents are removed, this issue will be marked as closed.
