### ISSUE TITLE
Couldn't run the provided script while defining the configuration

### ISSUE THREAD

**Issue by ethanhou99** [MicrosoftDocs/PowerShell-Docs-DSC#54]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for version of PowerShell DSC I am using.

### Version

3.0

### Link to affected document

https://docs.microsoft.com/en-us/powershell/dsc/getting-started/wingettingstarted?view=dsc-1.1#:~:text=Define%20a%20configuration%20and%20generate%20the%20configuration%20document%3A

### Description of the documentation error

Hi,

I met the following problems while running the provided script in the doc:
![image](https://user-images.githubusercontent.com/43047951/163357100-4b4a995f-201d-4bbd-b987-3b3a49aaf512.png)

After module was imported:
![image](https://user-images.githubusercontent.com/43047951/163354367-1efbb2a5-d792-4bea-a355-a0d894ad2f31.png)

I'm using PS7.2, both PSDscResources and Environment are installed and imported.

Could you please tell me how to fix this issue?

Thanks

**Comment by michaeltlombardi** [comment]
Hi, @ethanhou99! Thanks for submitting this issue. I think the root of your problem here is that you're trying to use the `configuration` keyword in PowerShell 7.2 / with DSC v3. v3 is still in preview at this time.

The documentation you were reading is for DSC v1.1. The [getting started documentation for v3 is here](https://docs.microsoft.com/powershell/dsc/getting-started/getting-started?view=dsc-3.0) and does not mention the `configuration` keyword because it is not supported in v3.

Another significant change in DSC v3 is that only class-based DSC Resources are supported. While v3 is in preview, many resources have not yet been converted to be class-based. Unfortunately, this includes the `Environment` resource.

If you'd like to use the documentation you were reading, you'd need to use Windows PowerShell 5.1 and DSC v1.1, which ships with that version of PowerShell. To ensure it loads properly, you'll need to either uninstall the newer version of the PSDesiredStateConfiguration module or ensure you import it with the **MaximumVersion** parameter set to 1.1:

```powershell
Import-Module PSDesiredStateConfiguration -MaximumVersion 1.1
```

I'm going to close this issue for now, but if you have more questions or comments, please do let me know!
